### ISSUE TITLE
XAML is not working

### ISSUE THREAD

**Issue by hulluP** [Level28-de/MmImageLoading#1]
**Describe the bug**
in the sample the xaml version of the cached image is not working

**To Reproduce**
Steps to reproduce the behavior please clone our repo and add the code so that the issue can be reproduced:
1. clone following https://github.com/Level28-de/MmImageLoading
2. start sample 
4. image is not showing

**Expected behavior**
image should show

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: simulator 
 - OS: iOS and Android

**Additional context**

**Comment by FreakyAli** [comment]
Is this still an issue?

**Comment by hulluP** [comment]
yes

**Comment by FreakyAli** [comment]
So it only works on real devices?

**Comment by FreakyAli** [comment]
I recommend archiving this project since it seems you don't plan on maintaining it!
